# Generated by Django 5.1.4 on 2025-07-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email_alter_user_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_otp',
            field=models.CharField(blank=True, default=0, max_length=6),
            preserve_default=False,
        ),
    ]
